SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOT_SPEED = 500
PLAYER_ROCKET_SPEED = 800
PLAYER_ROCKET_COOLDOWN = 5

LIVES_RADIUS = 10

SHOT_RADIUS = 5
ROCKET_RADIUS = 10

POWER_UP_RADIUS = 15
POWER_UP_SPAWN_RATE = 60

EFFECT_STATUS = False
EFFECT_MAX_DURATION = 10